name: Setup lib Directory

on:
  workflow_dispatch:

jobs:
  create-folder:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: sixteen
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create directory and dummy file
        run: |
          mkdir -p prebuilts/samsung/p3sxxx/vendor/lib
          echo "Create an empty file." > prebuilts/samsung/p3sxxx/vendor/lib/dummy.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add
          git add prebuilts/samsung/p3sxxx/vendor/lib/dummy.txt
          
          # Commit
          if git diff --staged --quiet; then
            echo "Folder already exists."
          else
            git commit -m "patch: add some exynos9825 fixes"
            git push origin sixteen
          fi
