name: Import d2s from EternityROM
on: workflow_dispatch

jobs:
  import-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UN1CA Repository
        uses: actions/checkout@v6
        with:
          ref: sixteen
          token: ${{ secrets.MY_TOKEN }}

      - name: Fetch and Copy d2s
        run: |
          # 1. جلب مستودع EternityROM (فرع fifteen)
          git clone --depth 1 -b fifteen https://github.com/Ocin4ever/EternityROM.git /tmp/EternityROM
          
          # 2. التأكد من وجود مجلد target
          mkdir -p target
          
          # 3. مسح أي نسخة قديمة من d2s لتجنب التداخل
          rm -rf target/d2s
          
          # 4. نسخ المجلد الجديد d2s إلى المسار المطلوب
          cp -r /tmp/EternityROM/target/d2s target/

      - name: Configure Bot Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Update
        run: |
          # إضافة المجلد الجديد للمسرح (Stage)
          git add target/d2s
          
          if git diff --cached --quiet; then
            echo "No changes detected. The d2s folder is already up to date."
          else
            git commit -m "Import d2s target from EternityROM (Branch: fifteen)"
            # الرفع باستخدام التوكن لتجنب خطأ 403
            git push https://${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}.git sixteen
          fi
